### ISSUE TITLE
How to change the color of an error message?

### ISSUE THREAD

**Issue by hellojinwoo** [yudai-nkt/jupyterlab_city-lights-theme#101]
First of all, thank you for creating such a wonderful theme.

## Question 
- How to change the color of an error message, which is currently pink color?
- What should I do to change the color from pink to something else, such as white?

![image](https://user-images.githubusercontent.com/34431729/105606218-548ef800-5d98-11eb-905b-e8b96b875d47.png)

**Comment by yudai-nkt** [comment]
I don't think there are canonical ways of doing that. You would need to manually edit the theme you have installed.
