### ISSUE TITLE
Will you eventually support JupyterLab 2.2.8?

### ISSUE THREAD

**Issue by rogershijin** [yudai-nkt/jupyterlab_city-lights-theme#65]

**Comment by yudai-nkt** [comment]
@rogershijin  Sorry for not responding and being inactive on this repo. I've started working on this again, and now am trying to support v2 in #96 (eventually v3 as well). If you are still interested in this theme, please wait for a while.

**Comment by yudai-nkt** [comment]
v2.0.0 has now been released: https://www.npmjs.com/package/@yudai-nkt/jupyterlab_city-lights-theme/v/2.0.0
