### ISSUE TITLE
Have it supportted JupyterLab 3.x?

### ISSUE THREAD

**Issue by FkerYJ** [yudai-nkt/jupyterlab_city-lights-theme#89]

**Comment by yudai-nkt** [comment]
I've started working on this repository again, and first try to support v2 in #96. After v2 is released, I'll work on v3 support.

I need to investigate what are the theme-releated breaking changes between v1/v2 and v2/v3, so it may take a while. If you want to track the progress, please subscribe the PR above.

**Comment by yudai-nkt** [comment]
PR for v3 support can be tracked at #97.
